trigger:
  - master

pool:
  name: Default

steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'hello-world/pom.xml'
      goals: 'package'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-21-openjdk-amd64'
      mavenVersionOption: 'Default'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: 'None'
