trigger:
  - master

pool:
  name: Default  # Use your self-hosted agent pool name

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'hello-world/pom.xml'  # 👈 Your POM path
      goals: 'package'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-21-openjdk-amd64'  # 👈 Direct Java path
      mavenVersionOption: 'Default'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: 'None'
