
trigger:
  - master

pool:
  name: Default  # Use your self-hosted agent pool name here

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'hello-world/pom.xml'  # 👈 Your POM path
      goals: 'package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21'
      mavenVersionOption: 'Default'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: 'None'
